name: Simapp V2 Start
on:
  pull_request:
  merge_group:
  push:
    branches:
      - server_
      - release/**
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-arch: ["amd64", "arm", "arm64"]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true
        ###################
        #### Build App ####
        ###################
      - name: Simapp v2 start
        run: GOARCH=${{ matrix.go-arch }} bash ./simv2.sh
