name: Simapp V2 Start
on:
  pull_request:
  merge_group:
permissions:
  contents: read

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true
      - name: Build simapp
        run: make build
      - name: Simapp v2 start
        run: bash ./simv2.sh
